### ISSUE TITLE
WP JSON

### ISSUE THREAD

**Issue by NTShop** [A5hleyRich/wordpress-nginx#10]
You should update to not cache URLs that lead to /wp-json 

`	if ($request_uri ~* "/wp-admin/|/wp-json/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml") {
		set $skip_cache 1;
	}   `

**Comment by A5hleyRich** [comment]
Thanks, fixed in 1530e8c2be5a420

**Comment by raqqun** [comment]
I can't understand why wp-json have to be skiped. For all i know wordpress api is a public interface of wordpress much like the website itself. Why not assume that the same principles of caching apply to that endpoint too ?

**Comment by A5hleyRich** [comment]
I think it's safer to not cache data endpoints by default as it can cause unexpected behaviour.
