### ISSUE TITLE
Enable caching for webfonts

### ISSUE THREAD

**Issue by crebuh** [A5hleyRich/wordpress-nginx#11]
Hy Ashley,

I love this repository. Made a lot of our sites damn fast :+1: 

For one of our projects we are using webfonts like woff, woff2, eot or ttf files. So I added these extensions to the static-files.conf

When you allow pull requests I can create one otherwise here is the changed line:

> location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2|eot|ttf)$ {

Best Christofer, keep up the good work!

**Comment by A5hleyRich** [comment]
Cheers! Resolved in https://github.com/A5hleyRich/wordpress-nginx/commit/ca484fe861c4c24b4b1bc8da20847da73239ba17
