### ISSUE TITLE
Files global/server/security.conf and global/server/exclusions.conf are not used anywhere

### ISSUE THREAD

**Issue by vpant** [A5hleyRich/wordpress-nginx#16]
I am not sure if this is on purpose but in part 7 of [Hosting Wordpress Yourself](https://deliciousbrains.com/hosting-wordpress-yourself-nginx-security-tweaks-woocommerce-caching-auto-server-updates/) you suggest security tips like the ones that included at the file [global/server/security.conf](https://github.com/A5hleyRich/wordpress-nginx/blob/master/global/server/security.conf) but this file is not used anywhere in nginx.conf or files at sites-available directory.

**Comment by chesio** [comment]
Hi, both files are included via [global/server/defaults.conf](https://github.com/A5hleyRich/wordpress-nginx/blob/master/global/server/defaults.conf).
