### ISSUE TITLE
global/server/exclusions.conf causing issues with certbot auto renewal (Lets encrypt)

### ISSUE THREAD

**Issue by shyamjos** [A5hleyRich/wordpress-nginx#17]
```
# Deny all attempts to access hidden files such as .htaccess, .htpasswd, .DS_Store (Mac).
# Keep logging the requests to parse later (or to pass to firewall utilities such as fail2ban)

location ~ /\. {
	deny all;
}

```

above rule is causing issues with certbot , Is there a way to exclude single hidden folder eg: .well-known ?

**Nginx error**
`2018/01/28 17:06:25 [error] 3290#3290: *1316 access forbidden by rule,`
**certbot error**
` The client lacks sufficient authorization :: Invalid response from http://www.blog.com/**.well-known**/acme-challenge/8nYiIsdsdsd2cfLZwsdsdPxNhCA: "`

**Comment by chesio** [comment]
I have the following snippet my `nginx.conf`:

```
# Allow access to .well-know directory (necessary for letsencrypt certbot).
location ^~ /.well-known/ {
    allow all;
}
```

See also: https://stackoverflow.com/questions/34259548/how-to-disallow-access-to-all-dot-directories-except-well-known

**Comment by shyamjos** [comment]
thanks for the solution :+1:
