### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by BoyetDgte** [A5hleyRich/wordpress-nginx#36]
I would like to update the link and text to reflect the updated version and update link [Install WordPress on Ubuntu 20.04](https://spinupwp.com/hosting-wordpress-yourself-ssl-spdy/).

**Comment by BoyetDgte** [comment]
@bradt Can I have write access to update the minor change? Thank you.

Will only change

`[Install WordPress on Ubuntu 20.04](https://spinupwp.com/hosting-wordpress-yourself-ssl-spdy/)`

to 

`[Install WordPress on Ubuntu 22.04](https://spinupwp.com/install-wordpress-ubuntu/)`

**Comment by bradt** [comment]
Done 👍

**Comment by BoyetDgte** [comment]
Thanks Brad!

Done with the updates. https://github.com/spinupwp/wordpress-nginx/commit/b5f439c9cdac6514e31a6e8932ebeaba5e5c921b
