### ISSUE TITLE
Configuration test failed on security.conf

### ISSUE THREAD

**Issue by einsiol** [A5hleyRich/wordpress-nginx#5]
After using this for my nginx config structure and using multisite-subdomain.com as the structure for my enabled-site config I received a error message when testing the configuration: 

```
# nginx -t
nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/global/server/security.conf:8
nginx: configuration file /etc/nginx/nginx.conf test failed
```

I removed the inclution of the file in global/server/defaults.conf and was able to get error free test results. 

I have not touched any of the configs when testing the setup other than the basics from the instructions found on [deliciousbrains.com](deliciousbrains.com/hosting-wordpress-yourself-complete-nginx-configuration/)

**Comment by appskitchen** [comment]
I found the same error. Any idea how to solve it?

**Comment by A5hleyRich** [comment]
What version of Nginx are you using? The configs require 1.7.5+

**Comment by appskitchen** [comment]
I got it. Thanks
